name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  REPO_NAME: ${{ github.repository }}
  REPO_ORG: "oandrefonseca"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      # Login to DockerHub
      - name: Log into DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push scAgnostic Docker image
        id: build-scAgnostic
        uses: docker/build-push-action@v2
        with:
          context: rna
          file: "rna/scAgnostic.Dockerfile"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_ORG }}/scagnostic:${{ github.sha }}

      - name: Build and push scAligners Docker image
        if: success() && github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: rna
          file: "rna/scAligners.Dockerfile"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_ORG }}/scaligners:${{ github.sha }}

      - name: Build and push scRPackages Docker image
        if: success() && github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: rna
          file: "rna/scRPackages.Dockerfile"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_ORG }}/scrpackages:${{ github.sha }}

      - name: Build and push scRBase Docker image
        if: success() && github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: rna
          file: "rna/scRBase.Dockerfile"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_ORG }}/scrbase:${{ github.sha }}

      - name: Build and push scVariant Docker image
        if: success() && github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: rna
          file: "rna/scVariant.Dockerfile"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_ORG }}/scvariant:${{ github.sha }}
